vm_name_base = "Alpine-standard"
iso_image = "alpine-standard-3.18.2-x86.iso"
iso_checksum = "file:https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86/alpine-standard-3.18.2-x86.iso.sha256"
cpu = "x86"
virtualbox_guest_os_type = "Linux"
vmware_guest_os_type = "other5xlinux"
esxi_guest_os_type = "other5xlinux"
