ABI = "FreeBSD:14:i386"
arch = "i386"
DISTRIBUTIONS = "'base.txz kernel.txz'"
iso_checksum = "file:https://download.freebsd.org/releases/ISO-IMAGES/14.3/CHECKSUM.SHA256-FreeBSD-14.3-RELEASE-i386"
iso_name = "FreeBSD-14.3-RELEASE-i386-disc1.iso"
qemu_binary = "qemu-system-i386"
virtualbox_guest_os_type = "FreeBSD"
vmware_guest_os_type = "freebsd"
