vm_name_base = "Alpine-virt"
iso_image = "alpine-virt-3.15.8-x86.iso"
iso_checksum = "file:https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/x86/alpine-virt-3.15.8-x86.iso.sha256"
cpu = "x86"
virtualbox_guest_os_type = "Linux"
vmware_guest_os_type = "other5xlinux"
esxi_guest_os_type = "other5xlinux"
