arch = "i386"
iso_file_name = "NetBSD-8.3-i386.iso"
iso_checksum = "file:https://cdn.netbsd.org/pub/NetBSD/NetBSD-8.3/iso/SHA512"
package_arch = "i386"
qemu_binary = "qemu-system-i386"
virtualbox_guest_os_type = "NetBSD"
vmware_guest_os_type = "other"
