cpu = "i386"
virtualbox_guest_os_type = "OpenBSD"
vmware_guest_os_type = "other"
os_ver = "7.8"
iso_image = "install78.iso"
iso_checksum = "file:https://cdn.openbsd.org/pub/OpenBSD/7.8/i386/SHA256"
package_arch = "i386"
qemu_binary = "qemu-system-i386"
