iso_image = "alpine-standard-3.17.10-x86.iso"
iso_checksum = "file:https://dl-cdn.alpinelinux.org/alpine/v3.17/releases/x86/alpine-standard-3.17.10-x86.iso.sha256"
cpu = "x86"
virtualbox_guest_os_type = "Linux"
vm_name_base = "Alpine-standard"
vmware_guest_os_type = "other5xlinux"
esxi_guest_os_type = "other5xlinux"
