iso_image = "alpine-virt-3.17.4-aarch64.iso"
iso_checksum = "file:https://dl-cdn.alpinelinux.org/alpine/v3.17/releases/aarch64/alpine-virt-3.17.4-aarch64.iso.sha256"
cpu = "aarch64"
virtualbox_guest_os_type = "Linux_64"
vm_name_base = "Alpine-virt"
vmware_guest_os_type = "arm-other5xlinux-64"
esxi_guest_os_type = "arm-other5xlinux-64"
